<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-07-10
 * Time: 11:52
 */

namespace app\index\controller;


use think\Controller;
use think\Log;

class Interval extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function index()
    {
        ignore_user_abort(true);
        set_time_limit(0);
        Log::error('可以了');
        exit();

    }

    /**
     * 设置提醒
     * @throws \think\Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @throws \think\exception\PDOException
     */
    public function sec_tips()
    {
        ignore_user_abort(true);
        set_time_limit(0);
        $i = 1;
        do {
            $list = db('sec_tips')->where(['tips_time' => ['elt', time() + 5 * 60], 'status' => 0])->select();
            $token = [];
            foreach ($list as $l) {
                $t = model('user')->where('id', $l['user_id'])->value('jiguangToken');
                $token[] = $t;
            }
            if (count($token) > 0) {
                pushMess('你设置的抢购活动还有5分钟开启', ['id'=>'', 'url'=>'', 'scene'=>'sec_active'], [
                    "registration_id" => $token]);
                db('sec_tips')->where('tips_time', 'elt', time() + 5 * 60)->update(['status' => 1]);
            }
            sleep(300);
            $i++;
        } while (true);
    }

    /**
     * 检验订单有效期
     */
    public function checkOrderStatus()
    {
        ignore_user_abort(true);
        set_time_limit(0);
        $j = 1;
        do{
            model('order')->save(['order_status' => 3], ['create_time' => ['lt', time() - config('order_remain') * 60], 'pay_status' => 0]);
            sleep(60);
            $j++;
        }while(true);
    }

    public function downGoodsProp()
    {
        ignore_user_abort(true);
        set_time_limit(0);
        $t = 1;
        do{
            model('goods_prop')->where('create_time', 'lt', strtotime(date('Y-m-d')))->delete();
            model('shopcart')->where('prop_id', 'gt', 0)->delete();
            $t++;
            sleep(86400);
        } while(true);
    }
}