<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-20
 * Time: 10:31
 */

namespace app\app\controller;


use think\Controller;

class Pub extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 微信小程序登陆
     */
    public function loginByWeiXin()
    {
        $app_id = config('xiaochengxu.app_id');
        $app_secret = config('xiaochengxu.app_secret');
        $js_code = input('js_code');
        if (!$app_id || !$app_secret || !$js_code) {
            exit_json(-1, '参数错误');
        }
        $res = file_get_contents("https://api.weixin.qq.com/sns/jscode2session?appid=$app_id&secret=$app_secret&js_code=$js_code&grant_type=authorization_code");
        $res = json_decode($res, true);
        if (!$res['openid']) {
            exit_json(-1, '参数错误');
        }
        $session_key = $res['session_key'];
        $open_id = $res['openid'];

        $os = db('os')->where('open_id', $open_id)->find();
        if($os){
            db('os')->where('open_id', $open_id)->update(['session_key'=>$session_key]);
        }else{
            db('os')->insert(['open_id'=>$open_id, 'session_key'=>$session_key]);
        }
        $user = model('User')->where('open_id', $open_id)->find();
        if ($user) {
            exit_json(1, '请求成功', [
                'open_id' => $open_id,
                'status' => 1,
                'user_info'=>null
            ]);
        } else {
            exit_json(1, '请求成功', [
                'open_id' => $open_id,
                'status' => 0,
                'user_info'=>null
            ]);
        }
    }

    /**
     * 获取微信绑定手机号
     */
    public function getBindNum()
    {
        $app_id = config('xiaochengxu.app_id');
        $iv = input('iv');
        $encryptedData = input('encryptedData');
        $open_id = input('open_id');
        $session_key = db('os')->where('open_id', $open_id)->value('session_key');
        include VENDOR_PATH . 'WeiXin/wxBizDataCrypt.php';
        $pc = new \WXBizDataCrypt($app_id, $session_key);
        $errCode = $pc->decryptData($encryptedData, $iv, $data);
        if ($errCode == 0) {
            $data = json_decode($data, true);
            $telephone = $data['purePhoneNumber'];
            exit_json(1, '请求成功', ['telephone' => $telephone]);
        } else {
            exit_json(-1, '请求参数异常');
        }
    }

    /**
     * 小程序上传图片
     */
    public function uploadImage()
    {
        $file = request()->file('file');
        if ($file) {
            $info = $file->move(__UPLOAD__);
            if ($info) {
                $saveName = $info->getSaveName();
                $path = "/upload/" . $saveName;
                exit_json(1, '操作成功', ['image_url'=>__URL__.$path]);
            } else {
                // 上传失败获取错误信息
                exit_json(-1, $file->getError());
            }
        }else{
            exit_json(-1, '文件不存在');
        }

    }







}