<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/19
 * Time: 14:22
 */

namespace app\header\controller;

use think\Log;
use think\Request;

class Index extends ShopBase
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function index()
    {
        require_once APP_PATH . 'header/leftmenu.php';
        $shop_info = model('Header')->where('id', session(config('headerKey')))->find();
        $this->assign('leftmenu', $leftmenu);
        $this->assign('shopInfo', $shop_info);
        return $this->fetch();
    }

    /**
     * 城主退出
     */
    function logout()
    {
        session(config('headerkey'), null);
        cookie('header_id', null);
        cookie('header_pwd', null);
        return redirect(url('header/Index/index'));
    }

    /**
     * 更改密码
     */
    public function changePassword()
    {
        if (request()->isAjax()) {
            $admin_id = session(config('headerKey'));
            if ($admin_id) {
                $password = input('password');
                $new_password = input('new_password');
                $r = model('Header')->where('id', $admin_id)->find();
                if ($r['password'] != md5($password)) {
                    exit_json(-1, '密码错误');
                } else {
                    $res = $r->save(['password' => md5($new_password)]);
                    if ($res) {
                        session(config('headerKey'), null);
                        exit_json(1, '更改成功');
                    } else {
                        exit_json(-1, '更改失败');
                    }
                }
            } else {
                exit_json(-1, '用户不存在');
            }
        }
        return $this->fetch();
    }


    public function welcome()
    {
        return $this->fetch();
    }

    /**
     * 城主图片库
     */
    public function image()
    {
        return $this->fetch();

    }

    public function getImageList()
    {
        $page = input("page");
        $list = model("Image")->where("header_id", HEADER_ID)->page($page, 20)->select();
        exit_json(1, "请求成功", $list);
    }

    /**
     * 上传文件
     */
    public function uploadFile()
    {
        $file = request()->file("file");
        if ($file) {
            if (is_array($file)) {
                $file_url = [];
                foreach ($file as $item) {
                    $hash = $item->hash();
                    $r = model("Image")->where("header_id", HEADER_ID)->where("md5", $hash)->find();
                    if(!$r){
                        $info = $item->move(__UPLOAD__."/spread/");
                        $saveName = $info->getSaveName();
//                        $path = "https://www.ybt9.com/upload/spread/" . $saveName;
                        $path = __URL__."/upload/spread/" . $saveName;
                        $file_url[] = [
                            "image_url"=>$path,
                            "header_id"=>HEADER_ID,
                            "md5"=>$hash
                        ];
                    }
                }
                if(count($file_url)>0){
                    $res = model("Image")->saveAll($file_url);
                }else{
                    $res = true;
                }
            } else {
                $hash = $file->hash();
                $r = model("Image")->where("header_id", HEADER_ID)->where("md5", $hash)->find();
                if(!$r){
                    $info = $file->move(__UPLOAD__."/spread/");
                    $saveName = $info->getSaveName();
//                    $path = "https://www.ybt9.com/upload/spread/" . $saveName;
                    $path = __URL__."/upload/spread/" . $saveName;
                    $result_url = [
                        "image_url"=>$path,
                        "header_id"=>HEADER_ID,
                        "md5"=>$hash
                    ];
                    $res = model("Image")->save($result_url);
                }else{
                    $res = true;
                }
            }
        } else {
            $res = false;
        }
        if($res){
            exit_json();
        }else{
            exit_json(-1, "图片上传失败");
        }
    }

    /**
     * 删除图片
     */
    public function delImage()
    {
        $list = model("Image")->whereIn("image_url", input("idstr"))->select();
        foreach ($list as $value){
//            $path = str_replace("https://www.ybt9.com/upload", __UPLOAD__, $value["image_url"]);
            $path = str_replace("http://group.com/upload", __UPLOAD__, $value["image_url"]);
            if(file_exists($path)){
                @unlink($path);
            }
            $value->delete();
        }
        exit_json();
    }


}