<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/19
 * Time: 14:22
 */

namespace app\header\controller;


use app\common\model\RongYun;
use app\common\model\Shop;
use think\Request;

class Index extends ShopBase
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function index()
    {
        require_once APP_PATH . 'header/leftmenu.php';
        $shop_info = model('Header')->where('id', session(config('headerKey')))->find();
        $this->assign('leftmenu', $leftmenu);
        $this->assign('shopInfo', $shop_info);
        return $this->fetch();
    }

    /**
     * 城主退出
     */
    function logout()
    {
        session(config('headerkey'), null);
        cookie('header_id', null);
        cookie('header_pwd', null);
        return redirect(url('header/Index/index'));
    }

    /**
     * 更改密码
     */
    public function changePassword()
    {
        if (request()->isAjax()) {
            $admin_id = session(config('headerKey'));
            if ($admin_id) {
                $password = input('password');
                $new_password = input('new_password');
                $r = model('Header')->where('id', $admin_id)->find();
                if ($r['password'] != md5($password)) {
                    exit_json(-1, '密码错误');
                } else {
                    $res = $r->save(['password' => md5($new_password)]);
                    if ($res) {
                        session(config('headerKey'), null);
                        exit_json(1, '更改成功');
                    } else {
                        exit_json(-1, '更改失败');
                    }
                }
            } else {
                exit_json(-1, '用户不存在');
            }
        }
        return $this->fetch();
    }


    public function welcome()
    {
        return $this->fetch();
    }


}