<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-18
 * Time: 10:41
 */

namespace app\header\controller;


use think\Controller;

class Leader extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 申请团长记录列表
     */
    public function applyList()
    {

        $list = model('ApplyLeaderRecord')->where('header_id', session(config('headerKey')))->select();
        $this->assign('list', $list);
        return $this->fetch();
    }

    /**
     * 待处理申请记录
     */
    public function readyList()
    {

        return $this->fetch();
    }

    /**
     * 团长提现申请记录
     */
    public function withdrawList()
    {

        return $this->fetch();
        
    }





}