<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-18
 * Time: 10:08
 */

namespace app\header\controller;


use think\Controller;
use think\Log;

class Product extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 商品列表
     */
    public function index()
    {
        $list = model('Product')->where('header_id', session(config('headerKey')))->select();
        $this->assign('list', $list);
        return $this->fetch();
    }

    /**
     * 添加商品
     */
    public function add()
    {
        if (request()->isPost()) {
            $data = input('post.');
            $swiper = uploadFile('swiper');
            $swiper_index = input('swiper_type/a');
            $swiper_list = [];
            $data['header_id'] = session(config('headerKey'));
            model('Product')->allowField(['product_name', 'desc', 'header_id'])->save($data);
            $product_id = model('Product')->getLastInsID();
            if($swiper){
                if($swiper_index){
                    foreach ($swiper_index as $key => $item) {
                        $swiper_list[] = [
                            'type' => $item,
                            'url' => $swiper[$key],
                            'product_id' => $product_id
                        ];
                    }
                }
                model('ProductSwiper')->saveAll($swiper_list);
            }
            exit_json();
        }
        return $this->fetch();
    }

    /**
     * 商品编辑
     */
    public function edit()
    {
        $product_id = input('product_id');
        $product = model('Product')->where('id', $product_id)->find();
        if(request()->isAjax()){
            $data = input('post.');
            $swiper = uploadFile('swiper');
            $swiper_index = input('swiper_type/a');
            $swiper_list = [];
            if($swiper){
                if($swiper_index){
                    foreach ($swiper_index as $key => $item) {
                        $swiper_list[] = [
                            'type' => $item,
                            'url' => $swiper[$key],
                            'product_id' => $product_id
                        ];
                    }
                }
                model('ProductSwiper')->where('product_id', $product_id)->delete();
                model('ProductSwiper')->saveAll($swiper_list);
            }
            $product->allowField(['product_name', 'desc'])->save($data);
            exit_json();
        }
        $swiper_list = model('ProductSwiper')->where('product_id', $product_id)->select();
        $this->assign('item', $product);
        $this->assign('swiper_list', $swiper_list);
        return $this->fetch();
    }





}