<?php
/**
 * 商家登陆
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/20
 * Time: 9:20
 */

namespace app\header\controller;


use think\Controller;
use think\Log;

class Pub extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('sitename', config('sitename'));
    }

    public function test()
    {
        echo phpinfo();
        exit();
    }

    /**
     * 后台用户登陆
     * @return \think\response\View
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    function login()
    {
        if (request()->isAjax()) {
            $name = input('post.uname');
            $password = input('post.password');
            $remember = input('post.online');
            $shop = model('Header')->where('name', $name)->where('password', md5($password))->find();
            if ($shop) {
                if (!$shop['enable']) {
                    exit_json(-1, '账号被禁止使用，请联系管理员');
                }
                if ($remember) {
                    cookie('header_id', $shop['id']);
                    cookie('header_pwd', $shop['password']);
                }
                session(config('headerKey'), $shop['id']);
                exit_json(200, '登陆成功');
            } else {
                exit_json(-1, '用户名或密码错误');
            }
        } else {
            return view('login');
        }
    }

    /**
     * 根据id删除数据
     */
    function delData()
    {
        $ids = input('idstr');
        $table = input('table');
        $res = db($table)->where('id', 'in', $ids)->delete();
        if ($res) {
            exit_json();
        } else {
            exit_json('操作失败');
        }
    }

    /**
     * 上传文件
     */
    public function uploadFile()
    {

//        $img_url = uploadFile("file");
        $file = request()->file("file");
        $res = \Qiniu::UploadFile($file);
        if($res["err"] == 0){
            $img_url = $res["data"];
            $file_info = pathinfo($img_url);
            $extension = $file_info["extension"];
            $img_arr = ["jpg", "jpeg", "gif", "png", "bmp"];
            $video_arr = ["mp4", "avi", "rmvb"];
            if(in_array($extension, $img_arr)){
                $type = 1;
            }else if(in_array($extension, $video_arr)){
                $type = 2;
            }else{
                $type = 3;
            }
            exit_json(1, "上传成功", ["type"=>$type, "url" => $img_url]);
        }else{
            exit_json(-1, $res["msg"]);
        }

    }


}