<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-16
 * Time: 16:08
 */

namespace app\header\controller;


use think\Log;

class System extends ShopBase
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 小程序参数设置
     */
    public function wApp()
    {
        $w_app = model('WappConfig')->where('header_id', session(config('headerKey')))->find();
        if(request()->isAjax()){
            $data = $_POST;
            if($w_app){
                $res = $w_app->allowField(true)->save($data);
            }else{
                $data['header_id'] = session(config('leaderKey'));
                $res = model('WappConfig')->save($data);
            }
            if($res){
                exit_json();
            }else{
                exit_json(-1,'操作失败');
            }
        }
        $this->assign('w_app', $w_app);
        return $this->fetch();
    }


}